//print('<AMO FAZER EXERCICIO NO URI>')
//print('<    AMO FAZER EXERCICIO NO URI>')

console.log('<AMO FAZER EXERCICIO NO URI>')
console.log('<    AMO FAZER EXERCICIO NO URI>')
console.log('<AMO FAZER EXERCICIO >')
console.log('<AMO FAZER EXERCICIO NO URI>')
console.log('<AMO FAZER EXERCICIO NO URI    >')
console.log('<AMO FAZER EXERCICIO NO URI>')
console.log('<          AMO FAZER EXERCICIO >')
console.log('<AMO FAZER EXERCICIO           >')
